### ISSUE TITLE
Import recommended services into Mongo

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-mongo#35]
See example input JSON file here https://drive.google.com/drive/folders/1JBncpPForLrdFwi8yAeNsta3KjzaKuY9. The name of the input file is the topic id. The services in the file are the ones that are recommended as services for the given topic.

- [x] Write a script in JavaScript to read the per-topic json files.
- [x] For each file, the topic id is taken from the file name, and the service ids are taken from the `hits/service_id` field
- [x] Create a collection in mongo where each document has the topic id and a list of service ids

**Comment by rasmus-storjohann-PG** [comment]
The commits for this are labelled with #29

**Comment by brandon-PG** [comment]
Works as intended
