### ISSUE TITLE
Write script to prepare BC211 CSV file for import into Mongo

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-mongo#4]
- [ ] Change CVS headers of service data files
- [ ] combine fields into objects and arrays: geolocation, address, phone numbers
- [ ] convert the file into json
- [ ] import file into mongo

This should be a python script to fix the header (work is mostly done) and a bash script that calls the puthon script, csvtojson, etc...

tools: python / iconv / csvtojson / mongimport / bash

**Comment by brandon-PG** [comment]
Script works as intended
