### ISSUE TITLE
13 Services which are over the 10,000 byte algolia limit

### ISSUE THREAD

**Issue by brandon-PG** [pg-irc/pathways-mongo#59]
50687444_bc
50727048_bc
50687430_bc
50664154_bc
51265377_bc
50705038_bc
51265380_bc
50664278_bc
50637603_bc
50727247_bc
50637624_bc
51265380_bc
44806913_mb

AC:
- [ ] These records are truncated so their size is less than 9.5K (to be sure), do this by truncating the service description and organization description field, whichever is longer.

**Comment by rasmus-storjohann-PG** [comment]
This should just work(TM) with the new Algolia subscription that increases the limit to 100K/record. Confirm this in staging.

**Comment by brandon-PG** [comment]
We still remove 12 records from the services collection. See https://github.com/pg-irc/pathways-mongo/pull/71 @rasmus-storjohann-PG
