### ISSUE TITLE
Invalid generated mark down

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-mongo#65]
Input: `Or go to: **[MB 211](https://mb.211.ca/)**\n\n`, leads to the first 211 being clickable and the URL not, like so:

 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/32307781/141165547-67f6418e-fea8-49c4-b1a8-809414e32b32.png">

The solution is probably to not make `211` clickable, only the `2-1-1` format will be clickable.

**Comment by rasmus-storjohann-PG** [comment]
@Farouk-PG please check that the links shown in the screenshot above are fixed. Also check that "211" is not clickable in the app, but "2-1-1" and "2 1 1" is, and that they click through to call the phone number. This pattern should apply to 911, 311, 811, etc.

**Comment by Farouk-PG** [comment]
Closing. This is fixed!
