### ISSUE TITLE
Service record over algolia data limit size

### ISSUE THREAD

**Issue by brandon-PG** [pg-irc/pathways-mongo#70]
There is one service record which cannot be uploaded to algolia due to its size being over the limit.

### Acceptance Criteria 
- [ ]  Verify all service records are under the algolia size limit.

**Comment by rasmus-storjohann-PG** [comment]
We made a change to the Algolia subscription that should make this problem go away. Marking this issue as "Staging" for now, let's check if it really is fixed before we make any code changes.

**Comment by rasmus-storjohann-PG** [comment]
Dupe of #59 no?

**Comment by brandon-PG** [comment]
Release 1.89.0 uses records which used to be over the size limit with no issues
