### ISSUE TITLE
MB questionnaire missing topic and showing extra ones - case 1

### ISSUE THREAD

**Issue by Farouk-PG** [pg-irc/pathways-mongo#78]
Clear all data from the app (go to ? Help, Clear all Data). Go to questionnaire. On Question 6, Select answer "I want to rent a place to live" and nothing else. Confirm that recommended topics that show up are: 1.1 Manitoba Start & Settlement agencies, 1.2 General information, 2.1 Types of housing, 2.2 Emergency housing and shelters, 2.3 Finding a place to rent, 2.4 Know your rights as a tenant, Subsidized and low-cost housing, "Opening a bank account", "Social insurance number", "Canadian money and banking" , "Credit and credit history" 

The above results in:

Missing 'Subsidized and low-cost housing'. Recommends extra topics 'Francophone settlement services', 'Household waste management', 'In your community: Recreation centres, Public libraries, Canada...', 'Buying food', 'Continuing education for adults', 'Vaccinations', and 'Public transportation'

Acceptance criteria:

- [x] Shows 'Subsidized and low-cost housing'
- [x] Doesn’t show extra topics 'Francophone settlement services', 'Household waste management', 'In your community: Recreation centres, Public libraries, Canada...', 'Buying food', 'Continuing education for adults', 'Vaccinations', and 'Public transportation'

**Comment by alysha-PG** [comment]
See changes we were going to make before MB Release but then decided not to here:
https://github.com/PeaceGeeksSociety/content/pull/861
https://github.com/pg-irc/pathways-frontend/pull/1769
