### ISSUE TITLE
MB questionnaire shows additional topics - case 2

### ISSUE THREAD

**Issue by Farouk-PG** [pg-irc/pathways-mongo#79]
**Part 1**:
Clear all data from the app (go to ? Help, Clear all Data). Go to questionnaire. On Question 4, mark that you have all documents. On Question 7, Select answer "Intermediate". On Question 8, mark "Fluent" and nothing else. Confirm that recommended topics that show up are: 1.1 Manitoba Start & Settlement agencies, 1.2 General information, 5.6 Register for language classes, 5.7 Continuing education for adults, and 6.1 Francophone settlement services

**Result**: 
Shows additional topics including 'Opening a bank account', 'Social insurance number', 'Household waste management', 'Types of housing', 'In your community: Recreation centres...', 'Weather in Manitoba', 'Buying food', 'Credit and credit history', 'Canadian money and banking', 'Vaccinations', and 'Public transportation'

**Acceptance**:
- [x] Remove unwanted additional topics

**Part 2**:
Clear all data from the app (go to ? Help, Clear all Data). Go to questionnaire. On Question 2, Select answer "Less than 1 year". On Question 4, mark that you have all documents.  Confirm that recommended topics that show up are: 1.1 Manitoba Start & Settlement agencies, 1.2 General information, 1.5 Weather in Manitoba, 1.7 Buying food, 1.8 In your community: Recreation centres, Public libraries, Canada Post, 2.1 Types of housing, 2.7 Household waste management, 3.1 Canadian money and banking, 4.7 Vaccinations, 7.5 Public transportation

**Result**:
Shows additional topics including 'Credit and credit history', 'Opening and bank account', 'Francophone settlement services', and 'Continuing education for adults'

**Acceptance**:
- [ ] Remove unwanted additional topics

**Comment by brandon-PG** [comment]
In part 1 I still see 'Opening a bank account', 'Social insurance number', 'Credit and credit history', 'Canadian money and banking', and 'Immigrating to Canada.

**Comment by brandon-PG** [comment]
In part 2 I still see 'Immigrating to Canada', 'Opening a bank account', 'Social insurance number', 'Credit and credit history', and 'Opening and bank account'. I do not see 'Household waste management'.

**Comment by brandon-PG** [comment]
These issues stem from the inverted questions in the questionnaire which do not work when selected. Removing them will require string changes with the accompanying translations.

**Comment by alysha-PG** [comment]
it's finally fixed, woo!
